ALTER TABLE "ReturnSettings"
ADD COLUMN IF NOT EXISTS "maintenanceEvidenceDays" INTEGER NOT NULL DEFAULT 120,
ADD COLUMN IF NOT EXISTS "maintenancePurgeDays" INTEGER NOT NULL DEFAULT 180,
ADD COLUMN IF NOT EXISTS "maintenanceBatchSize" INTEGER NOT NULL DEFAULT 200;
