ALTER TABLE "ReturnSettings"
ADD COLUMN IF NOT EXISTS "financeProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS "financeTaxPercent" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS "financeShopifyCommission" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN IF NOT EXISTS "financeOperationalCost" DOUBLE PRECISION NOT NULL DEFAULT 15,
ADD COLUMN IF NOT EXISTS "financeTransactionPercent" DOUBLE PRECISION NOT NULL DEFAULT 3;

CREATE TABLE IF NOT EXISTS "FinancePriceSettingsVersion" (
  "id" SERIAL PRIMARY KEY,
  "shop" TEXT NOT NULL,
  "profitPercent" DOUBLE PRECISION NOT NULL DEFAULT 50,
  "taxPercent" DOUBLE PRECISION NOT NULL DEFAULT 10,
  "shopifyCommission" DOUBLE PRECISION NOT NULL DEFAULT 3,
  "operationalCost" DOUBLE PRECISION NOT NULL DEFAULT 15,
  "transactionPercent" DOUBLE PRECISION NOT NULL DEFAULT 3,
  "effectiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "FinancePriceSettingsVersion_shop_effectiveAt_idx"
ON "FinancePriceSettingsVersion"("shop", "effectiveAt");
