ALTER TABLE "ReturnSettings"
ADD COLUMN IF NOT EXISTS "stockProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS "stockTaxPercent" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS "stockShopifyCommission" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN IF NOT EXISTS "stockOperationalCost" DOUBLE PRECISION NOT NULL DEFAULT 15,
ADD COLUMN IF NOT EXISTS "stockTransactionPercent" DOUBLE PRECISION NOT NULL DEFAULT 3;
