ALTER TABLE "ReturnSettings"
ADD COLUMN IF NOT EXISTS "financeHighProfitThreshold" DOUBLE PRECISION NOT NULL DEFAULT 750,
ADD COLUMN IF NOT EXISTS "financeHighProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 40,
ADD COLUMN IF NOT EXISTS "financeVeryHighProfitThreshold" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN IF NOT EXISTS "financeVeryHighProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 35;

ALTER TABLE "FinancePriceSettingsVersion"
ADD COLUMN IF NOT EXISTS "highProfitThreshold" DOUBLE PRECISION NOT NULL DEFAULT 750,
ADD COLUMN IF NOT EXISTS "highProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 40,
ADD COLUMN IF NOT EXISTS "veryHighProfitThreshold" DOUBLE PRECISION NOT NULL DEFAULT 1000,
ADD COLUMN IF NOT EXISTS "veryHighProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 35;
